library(raster)
library(dismo)
library(rpart)
library(maptools)
library(data.table)
library(rgdal)
library(dplyr)
library(sf)
library(fasterize)

## For NNS management unit ####

LCC <- CRS("+proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")
NNS <- raster("D:/CHID regional NS BRT/spatial/NNS.tif") 

disNNS <- disaggregate(NNS,fact=10)
disNNS

wt1<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_01/wtbl.shp")
wt1<-spTransform(wt1,LCC)
wt1_sf<-st_as_sf(wt1)
wt1r<-fasterize(wt1_sf,NNS,field="Depth")
wt1rdis<-fasterize(wt1_sf,disNNS,field="Depth")
rm(wt1)
plot(wt1r)

wt2<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_02/wtbl.shp")
wt2<-spTransform(wt2,LCC)
wt2_sf<-st_as_sf(wt2)
wt2r<-fasterize(wt2_sf,NNS,field="Depth")
wt2rdis<-fasterize(wt2_sf,disNNS,field="Depth")
rm(wt2)
plot(wt2r)

wt3<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_03/wtbl.shp")
wt3<-spTransform(wt3,LCC)
wt3_sf<-st_as_sf(wt3)
wt3r<-fasterize(wt3_sf,NNS,field="Depth")
wt3rdis<-fasterize(wt3_sf,disNNS,field="Depth")
rm(wt3)

wt4<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_04/wtbl.shp")
wt4<-spTransform(wt4,LCC)
wt4_sf<-st_as_sf(wt4)
wt4r<-fasterize(wt4_sf,NNS,field="Depth")
wt4rdis<-fasterize(wt4_sf,disNNS,field="Depth")
rm(wt4)

wt5<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_05/wtbl.shp")
wt5<-spTransform(wt5,LCC)
wt5_sf<-st_as_sf(wt5)
wt5r<-fasterize(wt5_sf,NNS,field="Depth")
wt5rdis<-fasterize(wt5_sf,disNNS,field="Depth")
rm(wt5)

wt6<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_06/wtbl.shp")
wt6<-spTransform(wt6,LCC)
wt6_sf<-st_as_sf(wt6)
wt6r<-fasterize(wt6_sf,NNS,field="Depth")
wt6rdis<-fasterize(wt6_sf,disNNS,field="Depth")
rm(wt6)

wt7<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_07/wtbl.shp")
wt7<-spTransform(wt7,LCC)
wt7_sf<-st_as_sf(wt7)
wt7r<-fasterize(wt7_sf,NNS,field="Depth")
wt7rdis<-fasterize(wt7_sf,disNNS,field="Depth")
rm(wt7)

wt8<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_08/wtbl.shp")
wt8<-spTransform(wt8,LCC)
wt8_sf<-st_as_sf(wt8)
wt8r<-fasterize(wt8_sf,NNS,field="Depth")
wt8rdis<-fasterize(wt8_sf,disNNS,field="Depth")
rm(wt8)

wt9<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_09/wtbl.shp")
wt9<-spTransform(wt9,LCC)
wt9_sf<-st_as_sf(wt9)
wt9r<-fasterize(wt9_sf,NNS,field="Depth")
wt9rdis<-fasterize(wt9_sf,disNNS,field="Depth")
rm(wt9)

wt10<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_10/wtbl.shp")
wt10<-spTransform(wt10,LCC)
wt10_sf<-st_as_sf(wt10)
wt10r<-fasterize(wt10_sf,NNS,field="Depth")
wt10rdis<-fasterize(wt10_sf,disNNS,field="Depth")
rm(wt10)

wt11<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_11/wtbl.shp")
wt11<-spTransform(wt11,LCC)
wt11_sf<-st_as_sf(wt11)
wt11r<-fasterize(wt11_sf,NNS,field="Depth")
wt11rdis<-fasterize(wt11_sf,disNNS,field="Depth")
rm(wt11)

wt12<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_12/wtbl.shp")
wt12<-spTransform(wt12,LCC)
wt12_sf<-st_as_sf(wt12)
wt12r<-fasterize(wt12_sf,NNS,field="Depth")
wt12rdis<-fasterize(wt12_sf,disNNS,field="Depth")
rm(wt12)

wt13<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_13/wtbl.shp")
wt13<-spTransform(wt13,LCC)
wt13_sf<-st_as_sf(wt13)
wt13r<-fasterize(wt13_sf,NNS,field="Depth")
wt13rdis<-fasterize(wt13_sf,disNNS,field="Depth")
rm(wt13)

wt14<-readOGR("D:/CHID regional NS BRT/water_table/wtbl_14/wtbl.shp")
wt14<-spTransform(wt14,LCC)
wt14_sf<-st_as_sf(wt14)
wt14r<-fasterize(wt14_sf,NNS,field="Depth")
wt14rdis<-fasterize(wt14_sf,disNNS,field="Depth")
rm(wt14)

wtmerge<-mosaic(wt1r,wt2r,wt3r,wt4r,wt5r,wt6r,wt7r,wt8r,wt9r,wt10r,wt11r,wt12r,wt13r,wt14r, fun=max)
wtdismerge<-mosaic(wt1rdis,wt2rdis,wt3rdis,wt4rdis,wt5rdis,wt6rdis,wt7rdis,wt8rdis,wt9rdis,wt10rdis,wt11rdis,wt12rdis,wt13rdis,wt14rdis, fun=max)

unique(wtmerge@data@values)
unique(getValues(wtdismerge))

plot(wtmerge)
plot(wtdismerge)



plot(wtmerge_mask)

writeRaster(wtmerge_mask,"watertableNNS_LCC",format="GTiff",overwrite=TRUE)
writeRaster(wtdismerge,"disaggregated_25m_watertableNNS_LCC",format="GTiff",overwrite=TRUE)

### For entire province ####
load("D:/Avian data processed/BAM_data_package_August2019.RData")

ltNS<-raster("D:/CHID regional NS BRT/spatial/landtypes_NovaScotia.tif")
plot(ltNS)
NS2<-ltNS
NS2<-projectRaster(NS2,crs=LCC)
values(NS2)[!is.na(values(NS2))] <- 1
plot(NS2)

rm(list=setdiff(ls(),c("LCC","NS2")))
gc()

disNS2 <- disaggregate(NS2,fact=10)
disNS2

wt1<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_01/wtbl.shp")
wt1<-spTransform(wt1,LCC)
wt1_sf<-st_as_sf(wt1)
wt1r<-fasterize(wt1_sf,NS2,field="Depth")
wt1rdis<-fasterize(wt1_sf,disNS2,field="Depth")
rm(wt1)
plot(wt1r)
gc()

wt2<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_02/wtbl.shp")
wt2<-spTransform(wt2,LCC)
wt2_sf<-st_as_sf(wt2)
wt2r<-fasterize(wt2_sf,NS2,field="Depth")
wt2rdis<-fasterize(wt2_sf,disNS2,field="Depth")
rm(wt2)
plot(wt2r)
gc()

wt3<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_03/wtbl.shp")
wt3<-spTransform(wt3,LCC)
wt3_sf<-st_as_sf(wt3)
wt3r<-fasterize(wt3_sf,NS2,field="Depth")
wt3rdis<-fasterize(wt3_sf,disNS2,field="Depth")
rm(wt3)
gc()

wt4<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_04/wtbl.shp")
wt4<-spTransform(wt4,LCC)
wt4_sf<-st_as_sf(wt4)
wt4r<-fasterize(wt4_sf,NS2,field="Depth")
wt4rdis<-fasterize(wt4_sf,disNS2,field="Depth")
rm(wt4)
gc()

wt5<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_05/wtbl.shp")
wt5<-spTransform(wt5,LCC)
wt5_sf<-st_as_sf(wt5)
wt5r<-fasterize(wt5_sf,NS2,field="Depth")
wt5rdis<-fasterize(wt5_sf,disNS2,field="Depth")
rm(wt5)
gc()

wt6<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_06/wtbl.shp")
wt6<-spTransform(wt6,LCC)
wt6_sf<-st_as_sf(wt6)
wt6r<-fasterize(wt6_sf,NS2,field="Depth")
wt6rdis<-fasterize(wt6_sf,disNS2,field="Depth")
rm(wt6)
gc()

wt7<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_07/wtbl.shp")
wt7<-spTransform(wt7,LCC)
wt7_sf<-st_as_sf(wt7)
wt7r<-fasterize(wt7_sf,NS2,field="Depth")
wt7rdis<-fasterize(wt7_sf,disNS2,field="Depth")
rm(wt7)
gc()

wt8<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_08/wtbl.shp")
wt8<-spTransform(wt8,LCC)
wt8_sf<-st_as_sf(wt8)
wt8r<-fasterize(wt8_sf,NS2,field="Depth")
wt8rdis<-fasterize(wt8_sf,disNS2,field="Depth")
rm(wt8)
gc()

wt9<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_09/wtbl.shp")
wt9<-spTransform(wt9,LCC)
wt9_sf<-st_as_sf(wt9)
wt9r<-fasterize(wt9_sf,NS2,field="Depth")
wt9rdis<-fasterize(wt9_sf,disNS2,field="Depth")
rm(wt9)
gc()

wt10<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_10/wtbl.shp")
wt10<-spTransform(wt10,LCC)
wt10_sf<-st_as_sf(wt10)
wt10r<-fasterize(wt10_sf,NS2,field="Depth")
wt10rdis<-fasterize(wt10_sf,disNS2,field="Depth")
rm(wt10)
gc()

wt11<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_11/wtbl.shp")
wt11<-spTransform(wt11,LCC)
wt11_sf<-st_as_sf(wt11)
wt11r<-fasterize(wt11_sf,NS2,field="Depth")
wt11rdis<-fasterize(wt11_sf,disNS2,field="Depth")
rm(wt11)
gc()

wt12<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_12/wtbl.shp")
wt12<-spTransform(wt12,LCC)
wt12_sf<-st_as_sf(wt12)
wt12r<-fasterize(wt12_sf,NS2,field="Depth")
wt12rdis<-fasterize(wt12_sf,disNS2,field="Depth")
rm(wt12)
gc()

wt13<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_13/wtbl.shp")
wt13<-spTransform(wt13,LCC)
wt13_sf<-st_as_sf(wt13)
wt13r<-fasterize(wt13_sf,NS2,field="Depth")
wt13rdis<-fasterize(wt13_sf,disNS2,field="Depth")
rm(wt13)
gc()

wt14<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_14/wtbl.shp")
wt14<-spTransform(wt14,LCC)
wt14_sf<-st_as_sf(wt14)
wt14r<-fasterize(wt14_sf,NS2,field="Depth")
wt14rdis<-fasterize(wt14_sf,disNS2,field="Depth")
rm(wt14)
gc()

wt15<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_15/wtbl.shp")
wt15<-spTransform(wt15,LCC)
wt15_sf<-st_as_sf(wt15)
wt15r<-fasterize(wt15_sf,NS2,field="Depth")
wt15rdis<-fasterize(wt15_sf,disNS2,field="Depth")
rm(wt15)
gc()

wt16<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_16/wtbl.shp")
wt16<-spTransform(wt16,LCC)
wt16_sf<-st_as_sf(wt16)
wt16r<-fasterize(wt16_sf,NS2,field="Depth")
wt16rdis<-fasterize(wt16_sf,disNS2,field="Depth")
rm(wt16)
gc()

wt17<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_17/wtbl.shp")
wt17<-spTransform(wt17,LCC)
wt17_sf<-st_as_sf(wt17)
wt17r<-fasterize(wt17_sf,NS2,field="Depth")
wt17rdis<-fasterize(wt17_sf,disNS2,field="Depth")
rm(wt17)
gc()

wt18<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_18/wtbl.shp")
wt18<-spTransform(wt18,LCC)
wt18_sf<-st_as_sf(wt18)
wt18r<-fasterize(wt18_sf,NS2,field="Depth")
wt18rdis<-fasterize(wt18_sf,disNS2,field="Depth")
rm(wt18)
gc()

wt19<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_19/wtbl.shp")
wt19<-spTransform(wt19,LCC)
wt19_sf<-st_as_sf(wt19)
wt19r<-fasterize(wt19_sf,NS2,field="Depth")
wt19rdis<-fasterize(wt19_sf,disNS2,field="Depth")
rm(wt19)
gc()

wt20<-readOGR("D:/CHID regional NS BRT/spatial/water_table/wtbl_20/wtbl.shp")
wt20<-spTransform(wt20,LCC)
wt20_sf<-st_as_sf(wt20)
wt20r<-fasterize(wt20_sf,NS2,field="Depth")
wt20rdis<-fasterize(wt20_sf,disNS2,field="Depth")
rm(wt20)
gc()

wtmerge<-mosaic(wt1r,wt2r,wt3r,wt4r,wt5r,wt6r,wt7r,wt8r,wt9r,wt10r,wt11r,wt12r,wt13r,wt14r,wt15r,wt16r,wt17r,wt18r,wt19r,wt20r, fun=max)
wtdismerge<-mosaic(wt1rdis,wt2rdis,wt3rdis,wt4rdis,wt5rdis,wt6rdis,wt7rdis,wt8rdis,wt9rdis,wt10rdis,wt11rdis,wt12rdis,wt13rdis,wt14rdis,wt15rdis,wt16rdis,wt17rdis,wt18rdis,wt19rdis,wt20rdis, fun=max)

unique(wtmerge@data@values)
unique(getValues(wtdismerge))

plot(wtmerge)
plot(wtdismerge)


writeRaster(wtmerge,"D:/CHID regional NS BRT/spatial/watertableNovaScotia_LCC",format="GTiff",overwrite=TRUE)
writeRaster(wtdismerge,"D:/CHID regional NS BRT/spatial/disaggregated_25m_watertableNovaScotia_LCC",format="GTiff",overwrite=TRUE)
